name: flame_chess
description: Chess game made with Flame
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.2.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.29.0
  flutter_bloc: ^9.1.1
  flame_bloc: ^1.12.13

flutter:
  assets:
    - assets/images/DarkBishop.webp
    - assets/images/DarkKing.webp
    - assets/images/DarkKnight.webp
    - assets/images/DarkPawn.png
    - assets/images/DarkQueen.webp
    - assets/images/DarkRook.webp
    - assets/images/LightBishop.webp
    - assets/images/LightKing.webp
    - assets/images/LightKnight.webp
    - assets/images/LightPawn.webp
    - assets/images/LightQueen.webp
    - assets/images/LightRook.webp